---
- hosts: all
  roles:
  - Update
  - EpelRelease
  - PackageInstall
  - Usersconfig
  - RestartMachines
- hosts: debian11awx
  roles:
  - Hardening
  - CopyConfig
- hosts: dm, dw1, dw2
  roles:
  - DockerInstall
